# Generated by Django 5.0.6 on 2026-08-07 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="e.g. 'Add input validation to the /signup endpoint'")),
                ('repo_path', models.CharField(help_text='Absolute path to a local git repo', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('planning', 'planning'), ('coding', 'coding'), ('testing', 'testing'), ('review', 'review'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('planner', 'planner'), ('coder', 'coder'), ('tester', 'tester'), ('reviewer', 'reviewer')], max_length=20)),
                ('provider', models.CharField(blank=True, choices=[('gemini', 'gemini'), ('groq', 'groq'), ('none', 'none')], default='none', max_length=20)),
                ('input_context', models.JSONField(default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failure', 'failure')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='agents.task')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]
