# Generated by Django 5.0.6 on 2026-08-08 07:23
#
# Choices-only reorder after the pipeline moved from Gemini+Groq to Groq-only
# (see orchestrator/settings.py). `choices` is validation/display metadata, not
# schema -- this issues no DDL and rewrites no rows; "gemini" stays a valid
# choice so AgentRun rows written before the switch still render in /admin.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_task_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrun',
            name='provider',
            field=models.CharField(blank=True, choices=[('groq', 'groq'), ('none', 'none'), ('gemini', 'gemini')], default='none', max_length=20),
        ),
    ]
